list_person/list_person/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

list_person/main/urls.py
from django.urls import path
from .views import MainList

urlpatterns = [
    path('', MainList.as_view(), name='home')
]

list_person/users/urls.py
from django.urls import path
from . import views as userViews
import django.contrib.auth.views as authViews
from .views import ProfileUpdateView, ProfileDetailView, ProfileDeleteView

urlpatterns = [
    path('user/<str:slug>/del/', ProfileDeleteView.as_view(), name='profile_delete'),
    path('user/<str:slug>/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('user/<str:slug>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('reg/', userViews.register, name='reg'),
    path('profile/', userViews.profile, name='profile'),
    path('user/', authViews.LoginView.as_view(template_name='users/user.html'), name='user'),
    path('pass-reset/',
        authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'),
        name='pass-reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
        authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password_reset_complete/',
        authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password-reset/done/',
        authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
]

list_person/users/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image
from .data_field import WORKING_POSITION, FILIAL, DEPARTMENT
from django.utils import timezone
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField('ФИО', default='Иванов Иван', max_length=100)
    slug = models.SlugField(verbose_name='URL', max_length=255, blank=True, unique=True)
    images = models.ImageField('Фото профиля', default='default.jpg', upload_to='user_images')
    date = models.DateField('Дата вступление на работу', default=timezone.now)
    account_type = models.CharField('Должность', choices=WORKING_POSITION, default='Employee', max_length=20)
    filial = models.CharField('Филиал', choices=FILIAL, default='Moscow', max_length=20)
    department = models.CharField('Отделение', choices=DEPARTMENT, default='Developers', max_length=20)
    salary = models.IntegerField('Оклад', default=50000)

    def __str__(self):
        return f'Данные коллеги {self.user.username}'

    def get_absolute_url(self):
        return reverse('profile-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super().save()

        image = Image.open(self.images.path)

        if image.height > 256 or image.width > 256:
            resize = (256, 256)
            image.thumbnail(resize)
            image.save(self.images.path)

list_person/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserOurRegistraion(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class ProfileImage(forms.ModelForm):

    def __init__(self, *args, **kwards):
        super(ProfileImage, self).__init__(*args, **kwards)
        self.fields['images'].label = "Изображение сотрудника"

    class Meta:
        model = Profile
        fields = ['name', 'slug', 'images', 'account_type', 'filial', 'department', 'salary']


class ProfileImageDis(forms.ModelForm):

    def __init__(self, *args, **kwards):
        super(ProfileImageDis, self).__init__(*args, **kwards)
        self.fields['images'].label = "Изображение сотрудника"
        for field in self.fields.values():
            field.disabled = True

    class Meta:
        model = Profile
        fields = ['name', 'slug', 'images', 'account_type', 'filial', 'department', 'salary']

list_person/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserOurRegistraion, ProfileImage, UserUpdateForm, ProfileImageDis
from django.views.generic import DetailView, UpdateView, DeleteView
from django.db import transaction
from django.urls import reverse_lazy
from .models import Profile


def register(request):
    if request.method == "POST":
        form = UserOurRegistraion(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Аккаунт {username} был создан, введите имя пользователя и пароль для авторизации')
            return redirect('user')
    else:
        form = UserOurRegistraion()
    return render(request, 'users/registraion.html', {'form': form, 'title':'Регистрация пользователя'})


@login_required
def profile(request):
    if request.method == "POST":
        img_profile_dis = ProfileImageDis(request.POST, request.FILES, instance=request.user.profile)
        img_profile = ProfileImage(request.POST, request.FILES, instance=request.user.profile)
        update_user = UserUpdateForm(request.POST, instance=request.user)

        if update_user.is_valid() and img_profile.is_valid():
            update_user.save()
            img_profile.save()
            messages.success(request, f'Ваш аккаунт был успешно обновлен')
            return redirect('profile')
    else:
        img_profile = ProfileImage(instance=request.user.profile)
        img_profile_dis = ProfileImageDis(instance=request.user.profile)
        update_user = UserUpdateForm(instance=request.user)

    data = {
        'title': request.user.username,
        'img_profile': img_profile,
        'update_user': update_user,
        'img_profile_dis': img_profile_dis
    }

    return render(request, 'users/profile.html', data)


class ProfileDetailView(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'users/profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'{self.object.user.username}'
        return context


class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileImage
    template_name = 'users/profile_edit.html'

    def get_object(self, queryset=None):
        return Profile.objects.get(slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['title'] = f'Редактирование профиля пользователя: {self.get_object().user.username}'
        if self.request.POST:
            context['user_form'] = ProfileImage(self.request.POST, instance=self.get_object().user)
        else:
            context['user_form'] = ProfileImage(instance=self.get_object().user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context['user_form']
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                user_form.save()
                form.save()
            else:
                context.update({'user_form': user_form})
                return self.render_to_response(context)
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('profile_detail', kwargs={'slug': self.object.slug})


class ProfileDeleteView(DeleteView):
    model = Profile
    template_name = 'users/profile_del.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(ProfileDeleteView, self).get_context_data(**kwargs)
        context['title'] = f'Удаление профиля пользователя: {self.get_object().user.username}'
        return context

list_person/templates/users/exit.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Вы успешно вышли с аккаунта</h2>
    <a href="{% url 'user' %}">Войти в личный кабинет снова</a>
  </div>
{% endblock %}

list_person/templates/users/pass_reset.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Восстановление пароля</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn">Запросить новый пароль</button>
    </form>
  </div>
{% endblock %}

list_person/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Вы успешно обновили пароль</h2>
    <p>Ваш пароль заменен на новый!</p>
  </div>
{% endblock %}

list_person/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Восстановление пароля</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn">Установить пароль</button>
    </form>
  </div>
{% endblock main %}

list_person/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Вы успешно обновили пароль</h2>
    <p>Ваш пароль был отпарвлен вам на почту</p>
  </div>
{% endblock %}

list_person/templates/users/profile.html
{% extends 'base.html' %}
{% block main %}
  <div class="forms1">
    <h2>Кабинет пользователя</h2>
    <div class="media text-muted pt-3">
      <img class="mr-2 rounded" style="margin: 20px; width: 128px; height: 128px;" src="{{ user.profile.images.url }}">
      <h2>{{ profile.name }}</h2>
    </div>
    <form method="POST" enctype="multipart/form-data">
      <div>
        <h3 class="mt-4">Изменить данные про пользователя</h3>
        {% csrf_token %}
        {{ update_user }}
        {% if user.is_superuser %}
        {{ img_profile }}
        {% else %}
        {{ img_profile_dis }}
        {% endif %}
        <button type="submit" class="btn btn-dark">Обновить</button>
      </div>

    </form>
  </div>
{% endblock %}

list_person/templates/users/profile_del.html
{% extends 'base.html' %}

{% block main %}
      <div>
        {% if user.is_superuser %}
          <p>Вы уверены, что хотите удалить профиль {{ profile.name }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning">Удалить</button>
            <a href="{% url 'profile_detail' profile.slug %}">Отмена</a>
        </form>
          {% else %}
          <h3>Ошибка!!!</h3>
        {% endif %}
      </div>
{% endblock %}

list_person/templates/users/profile_detail.html
{% extends 'base.html' %}
{% block main %}
  <div class="forms">
    <h2>Кабинет пользователя</h2>
    <div class="media text-muted pt-3">
      <img class="mr-2 rounded" style="margin: 20px; width: 128px; height: 128px;" src="{{ profile.images.url }}">
      <h4>@{{ profile.user.username }}</h4>
    </div>
    <form>
      <div>
        <h2>{{ profile.name }}</h2>
        <p>Дата приема на работу: {{ profile.date }}</p>
        <p>Должность: {{ profile.get_account_type_display }}</p>
        <p>Филиал г.{{ profile.get_filial_display }}</p>
        <p>Отделение: {{ profile.get_department_display }}</p>
        <p>Оклад: {{ profile.salary }} P</p>
        {% if user.is_superuser %}
        <button type="button" class="btn btn-dark me-2"><a href="{% url 'profile_edit' profile.slug %}" class="text-white">Изменить</a></button>
        {% endif %}
      </div>

    </form>
  </div>
{% endblock %}

list_person/templates/users/profile_edit.html
{% extends 'base.html' %}
{% block main %}
  <div class="forms1">
    <div class="media text-muted pt-3">
      <img class="mr-2 rounded" style="margin: 20px; width: 128px; height: 128px;" src="{{ user.profile.images.url }}">
      <h3>{{ title }}</h3>
    </div>
    <form method="post" enctype="multipart/form-data">
      <div>
        <h3 class="mt-4">Изменить данные про пользователя</h3>
        {% csrf_token %}
        {{ user_form.as_p }}
        <button type="submit" class="btn btn-dark">Обновить</button>
      </div>

    </form>
  </div>
{% endblock %}

list_person/templates/users/registraion.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Регистрация на сайта</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn btn-dark ">Зарегистрироваться</button>
    </form>
    <hr>
    Уже зарегистрированы? <a href="{% url 'user' %}">Войти в личный кабинет</a>
  </div>
{% endblock %}

list_person/templates/users/user.html
{% extends 'base.html' %}

{% block main %}
  <div class="form-section container">
    <h2>Авторизация на сайте</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn btn-outline-dark">Войти</button>
    </form>
    Забыли пароль? <a href="{% url 'pass-reset' %}">Получите новый</a>
    <h4> </h4>
    Тут впервые? <a href="{% url 'reg' %}">Регистрация</a>
  </div>
{% endblock %}